Additional error handling in hooks

diff --git a/scripts/hooks/pre-commit b/scripts/hooks/pre-commit
--- a/scripts/hooks/pre-commit
+++ b/scripts/hooks/pre-commit
@@ -3,6 +3,9 @@
 if [ ! -f ./gradlew ]; then
   echo "Error: Gradle wrapper not found. Please run this script from the root of the project."
   exit 1
+else if [ ! -x ./gradlew ]; then
+  echo "Error: Gradle wrapper is not executable. Please make it executable with 'chmod +x ./gradlew'."
+  exit 1
 fi
 
 echo ""
